# Generated by Django 5.1.3 on 2024-12-04 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_remove_post_created_at_remove_post_image_post_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='comments', to='diary.post')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
