# Generated by Django 5.1.3 on 2024-12-04 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
