# Generated by Django 5.1.3 on 2024-12-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_reply_body_reply_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='body',
            field=models.TextField(),
        ),
    ]
