# Generated by Django 5.1.3 on 2024-12-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0011_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
