# Generated by Django 5.1.3 on 2025-02-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0013_comment_image_comment_video_post_image_post_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('clip', models.FileField(upload_to='videos/%Y/%m/%d/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
